export default {
  monday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
  tuesday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
  wednesday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
  thursday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
  friday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
  saturday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
  sunday: [
    { key: 1, startTime: '9:00 am', endTime: '10:00 am', period: 'am', selected: false },
    { key: 2, startTime: '10:00 am', endTime: '11:00 am', period: 'am', selected: false },
    { key: 3, startTime: '11:00 am', endTime: '12:00 pm', period: 'am', selected: false },
    { key: 4, startTime: '12:00 pm', endTime: '1:00 pm', period: 'pm', selected: false },
    { key: 5, startTime: '1:00 pm', endTime: '2:00 pm', period: 'pm', selected: false },
    { key: 6, startTime: '2:00 pm', endTime: '3:00 pm', period: 'pm', selected: false },
    { key: 7, startTime: '3:00 pm', endTime: '4:00 pm', period: 'pm', selected: false },
    { key: 8, startTime: '4:00 pm', endTime: '5:00 pm', period: 'pm', selected: false },
    { key: 9, startTime: '5:00 pm', endTime: '6:00 pm', period: 'pm', selected: false },
    { key: 10, startTime: '6:00 pm', endTime: '7:00 pm', period: 'pm', selected: false },
    { key: 11, startTime: '7:00 pm', endTime: '8:00 pm', period: 'pm', selected: false },
    { key: 12, startTime: '8:00 pm', endTime: '9:00 pm', period: 'pm', selected: false },
    { key: 13, startTime: '9:00 pm', endTime: '10:00 pm', period: 'pm', selected: false },
  ],
};
