version: 2
jobs:
  build:
    working_directory: ~/toktumi
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: amann11/circleci-node-aws:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies with yarn wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build create-react-app
          command: cd packages/client && yarn build
      - run:
          name: Deploy to staging aws environment
          command: serverless deploy --stage staging
  test:
    steps:
      - checkout
      - run:
          name: Haha I should be testing stuff
          command: echo Funny how many tests there are wow!
  deploy-aws:
    steps:
      - checkout
      - run: 
          name: I should be deploying to aws
          command: echo Deploying aws staging
     
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master