service: toktumi-serverless

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:NODE_ENV}
  region: us-east-1
  profile: toktumi

# you can add packaging information here
package:
  individually: true
  exclude:
    - .gitignore
    - package.json
    - node_modules/**
  include:

functions:
  scapholdLogicExpressApi:
    handler: src/scapholdLogicExpressApi/lib.default
    environment:
      POSTMARK_API_KEY: 39f2eefa-fc15-491e-be83-64a3ec84a4cc
      TYPEFORM_API_KEY: 133cd26567475cc5be624aa3db0a81b4b4536509
    events: # The Events that trigger this Function
      - http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function.  Learn more in "events/apigateway"
          path: scaphold/{proxy+} # Path for this endpoint
          method: any # HTTP method for this endpoint
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
