/**
 * Created by alexandermann on 2017-01-27.
 */
export const BEGIN_FETCH_INVITE_REQUESTS = 'BEGIN_FETCH_INVITE_REQUESTS';
export const FETCH_INVITE_REQUESTS_SUCCESS = 'FETCH_INVITE_REQUESTS_SUCCESS';
export const FETCH_INVITE_REQUESTS_FAILURE = 'FETCH_INVITE_REQUESTS_FAILURE';
export const UNCHECK_INVITE_REQUEST = 'UNCHECK_INVITE_REQUEST';
export const CHECK_INVITE_REQUEST = 'CHECK_INVITE_REQUEST';
