/**
 * Created by alexandermann on 2017-01-31.
 */
export const FETCH_UPCOMING_CONNECTIONS = 'FETCH_UPCOMING_CONNECTIONS';
export const RESEND_VERIFICATION_EMAIL  = 'RESEND_VERIFICATION_EMAIL';
export const FETCH_UPCOMING_CONNECTIONS_SUCCESS  = 'FETCH_UPCOMING_CONNECTIONS_SUCCESS';
export const REQUEST_CONNECTION  = 'REQUEST_CONNECTION';
