service: toktumi-serverless-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs6.10
  # if ${opt:stage} is not specified will default to the value of dev see: https://serverless.com/framework/docs/providers/aws/cli-reference/deploy#deployment-without-stage-and-region-options
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  timeout: 60

  # you can define service wide environment variables here, same as .env
  environment:
    GRAPHCOOL_SIMPLE_ENDPOINT: ${env:GRAPHCOOL_SIMPLE_ENDPOINT}
    GRAPHCOOL_SUBSCRIPTION_ENDPOINT: ${env:GRAPHCOOL_SUBSCRIPTION_ENDPOINT}
    GRAPHCOOL_AUTH_TOKEN: ${env:GRAPHCOOL_AUTH_TOKEN}
    POSTMARK_API_KEY: ${env:POSTMARK_API_KEY}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_VIDEO_API_KEY_SID: ${env:TWILIO_VIDEO_API_KEY_SID}
    TWILIO_VIDEO_API_KEY_SECRET: ${env:TWILIO_VIDEO_API_KEY_SECRET}
    TWILIO_CHAT_SERVICE_SID: ${env:TWILIO_CHAT_SERVICE_SID}
    EMAIL_TO_SEND_FROM: ${env:EMAIL_TO_SEND_FROM}

package:
  include:
    - node_modules/**

functions:
  express-server:
    name: ${self:provider.stage}-api
    description: An express app to handle graphcool and app backend functionality
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+} # Path for this endpoint
          method: any # HTTP method for this endpoint
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
